[package]
name = "todoapp1"
version = "0.1.0"
authors = ["forfd8960 <forfd8960@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.21.0" }
